### PR TITLE
ci.cmd: Set c and cxx compiler to cl.exe

### PR DESCRIPTION
**Pull request by aniketmitra001**

### CODE REVIEW

**Comment by bacusters** [comment]
Is this blocked by another PR?

**Comment by aniketmitra001** [comment]
> Is this blocked by another PR?

I haven't able to get it to work with GitHub workflows yet

**Comment by bacusters** [comment]
> 
> 
> > Is this blocked by another PR?
> 
> I haven't able to get it to work with GitHub workflows yet

Ah ok. Anything I can help with?

**Comment by aniketmitra001** [comment]
> > > Is this blocked by another PR?
> > 
> > 
> > I haven't able to get it to work with GitHub workflows yet
> 
> Ah ok. Anything I can help with?

Sure, I think the ```ci.cmd``` script is broken. If you have already built MoveTK on windows and have some ideas for fixing it, that would be great!

**Comment by bacusters** [comment]
According to the build log, the virtual environment is given by [this](https://github.com/actions/virtual-environments/blob/win19/20200827.1/images/win/Windows2019-Readme.md), which apparently contains Visual Studio 2019. So I guess we should use the path given there to find the C and C++ compiler and the vcvarsall.bat? Currently, CMake seems to not detect the compiler correctly.
The path to the C/CXX compiler would then be  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29016\bin\Hostx64\x64\cl.exe if I'm correct. The vcvars should be in C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars[all|32|64].bat. This I extrapolate from my own VS19 setup, since I don't see a way to recreate the virtual environment locally. @aniketmitra001 do you have any way to locally checkout the virtual environment?

**Comment by bacusters** [comment]
The Windows CI seems to be building with the correct compiler now. However, the CGAL dependency now complains (this issue https://github.com/microsoft/vcpkg/issues/14238), so we would need to upgrade vcpkg in the virtual environment before installing the dependencies. Here, I see the following problem: if we do this, we are always pulling in the latest versions of the dependencies, which makes caching of the installed dependencies (which we may want to do given build time). In addition, the check now depends on the versions of other libraries. We may want to have a look at providing custom ports (https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md) for our dependencies, so that their version is at least fixed until we bump it ourselves. @aniketmitra001 what do you think is a good approach here?

**Pull request merged**
